# Generated by Django 3.2.4 on 2021-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.ImageField(default='programmer.jpg', upload_to=''),
        ),
    ]
